language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-support
  - extra
  - extra-android-m2repository
script:
  - ./gradlew clean assembleDebug
  - ./gradlew clean assembleRelease